import type { Metadata } from "next";
import Hero from "@/components/sections/Hero";
import UseCaseCards from "@/components/sections/UseCaseCards";
import Button from "@/components/ui/Button";

export const metadata: Metadata = {
  title: "Use Cases \u2014 Gradeum for Agencies",
  description:
    "Port authorities, cities, counties, DOTs, USCG. Real scenarios showing how Gradeum retrieves decades of engineering records in seconds.",
};

const disclaimerText =
  "This response was generated by Gradeum, Inc. All outputs are AI-assisted document retrieval from your organization\u2019s archived records. Retrieved documents reflect their original date of record and may not represent current conditions. Consult a licensed professional engineer before using archived documents for design, construction, or regulatory decisions. Gradeum does not exercise engineering judgment.";

export default function UseCasesPage() {
  return (
    <>
      <Hero
        headline="Built for the organizations that build communities"
        sub="Every agency has decades of engineering records. Gradeum makes them useful again."
        primaryCTA={{ label: "Get Started", href: "/agencies/pricing" }}
      />

      <UseCaseCards />

      {/* Disclaimer callout */}
      <section className="max-w-3xl mx-auto px-6 pb-20">
        <div className="bg-navy-deep rounded-2xl p-8 md:p-10">
          <p className="text-amber text-xs font-bold tracking-widest uppercase mb-4">
            Every response includes this disclaimer. Always.
          </p>
          <p className="text-white/80 text-sm leading-relaxed font-serif italic">
            {disclaimerText}
          </p>
        </div>
      </section>

      <section className="py-16 text-center px-6">
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Button href="/agencies/pricing" size="lg">
            Get Started
          </Button>
          <Button href="/agencies/contact" variant="secondary" size="lg">
            Contact Us
          </Button>
        </div>
      </section>
    </>
  );
}
